# Generated by Django 2.2.2 on 2019-06-25 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=80)),
                ('complete_name', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=80)),
                ('street', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('museum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museum.Museum')),
            ],
        ),
    ]
