name: Musaeum Client build app

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Nodejs
      uses: actions/checkout@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        cd client
        npm install

    - name: Run unit tests
      run: |
        cd client
        npm run test:unit
